version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: The hosts's id. References the host table.
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        description: Type of the apartment / room
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
                
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb host details.
    columns:
      - name: host_id
        description: The id of the host. This is the primary key.
        data_tests:
          - not_null
          - unique

      - name: host_name
        description: the name of the host.
        data_tests:
          - not_null

      - name: is_superhost
        description: Defines whether the hosts is a superhost.
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f']        

  - name: dim_listings_w_hosts
    description: transformed table which contains Airbnb host and listing details.
    data_tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: number

          - dbt_expectations.expect_column_quantile_values_to_be_between:
              arguments:
                quantile: .99
                min_value: 50
                max_value: 500

          - dbt_expectations.expect_column_max_to_be_between:
              arguments:
                max_value: 5000
              config:
                severity: warn

  - name: fct_reviews
    columns:
      - name: review_id
        data_tests:
          - not_null
          - unique
      - name: review_date
        data_tests:
          - not_null

  - name: mart_fullmoon_reviews
    description: fact table which contains host review info after full-moon.            